閉写像に関する節の命題の証明と具体例の構成
ykyki/extop-tex pull request #104
Opened 2022-01-22 06:17 UTC by CptHaus

## 背景・意図

- 内容の充実

## したこと

- 閉写像どうしの積写像が閉にならない例の構成
- 可算コンパクト空間Xと列型空間Yの積空間からYへの射影が閉写像であることの証明

## プルリク提出前: 確認事項

- [ ] 変更箇所の動作確認・表示確認
- [ ] reviewersやassignees等の設定
- [ ] このプルリクのプレビュー
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] 以上の項目がチェックされているか

## リバイズ進行状態

1. [ ] 文章の配置場所やレイアウト
2. [ ] 数学的な内容
3. [ ] 誤植や言葉使いなど文章の細部
4. [ ] 出典の記載
5. [ ] コマンドの使い方
6. [ ] ソースコードのフォーマット

2022-03-13 05:39 UTC, ykyki commented
🆗 文章の配置場所やレイアウト

2022-03-13 05:39 UTC, ykyki commented
数学的な内容

レビューしたファイルを送信したので確認お願いします。

2022-03-22 13:46 UTC, CptHaus commented
PDFに書き込んだレビューに対応しました.

2022-04-09 11:00 UTC, ykyki reviewed
OK
- 数学的な内容

2022-04-09 11:00 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	このとき, 恒等写像$ \morph{id}{Y}{Y} $と$ f $は閉写像であるが
恒等写像 id を表すコマンドの定義をお願いします。
（後続タスクでグローバルコマンドに追加します。）

2022-04-09 11:00 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ Y $がk-空間であることから$ \mapset{f}{F} $は$ Y $の閉集合である.
k-空間ではなく、Yの仮定が根拠ですね。

2022-04-09 11:00 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ x $の任意の開近傍$ U $について$ U \cap A $は無限集合である.
U \cap A が無限集合であることの証明は、命題 1.4.3に任せてしまっていいと思います。

2022-04-16 10:12 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	このとき, 恒等写像$ \morph{id}{Y}{Y} $と$ f $は閉写像であるが
\newcomman{\identity}{\mathrm{id}} を定義しました.

2022-04-16 10:12 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ Y $がk-空間であることから$ \mapset{f}{F} $は$ Y $の閉集合である.
対応しました.

2022-04-16 10:13 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ x $の任意の開近傍$ U $について$ U \cap A $は無限集合である.
対応しました.

2022-04-16 10:13 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ Y $がk-空間であることから$ \mapset{f}{F} $は$ Y $の閉集合である.
\mapset{f}{K \cap \mapinvset{f}{K}} -> \mapset{f}{F \cap \mapinvset{f}{K}} の修正も行いました.

2022-04-16 10:14 UTC, CptHaus commented
レビューコメントに対応したので確認をお願いします.

2022-04-16 11:10 UTC, ykyki requested changes
checked:
- 誤植や言葉使いなど文章の細部

2022-04-16 11:10 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
>  	各$ \morph{f_i}{X_i}{Y_i} $は閉写像である.
変更範囲外ですが、自明な誤植がありました…。

2022-04-16 11:10 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	ここで, $ \morph{f}{X}{\{0\}} $を$ X $から１点のみの空間$ \{0\} $への写像とする.
「1点のみの空間」→「一点空間」で圧縮してしまっていいかも？

2022-04-16 11:10 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	よって, $ Y $に関する仮定より$ \mapset{f}{F} $は$ Y $の閉集合である.
```suggestion
	よって, $ Y $の仮定より$ \mapset{f}{F} $は$ Y $の閉集合である.
```

2022-04-16 11:11 UTC, ykyki commented
OK: 出典の記載

2022-04-16 11:14 UTC, ykyki requested changes
cheked:
- コマンドの使い方

2022-04-16 11:14 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	$ \mapset{f \times \identity}{F} = \{0\} \times \mapset{p}{F} $は閉でない.
```suggestion
	$ \mapset{f \times \identity}{F} = \lrbrace{0} \times \mapset{p}{F} $は閉でない.
```

2022-04-23 11:43 UTC, ykyki commented
こちらの対応もお願いします 🙇 
https://github.com/ykyki/extop-tex/pull/104#discussion_r851616093

2022-04-23 11:43 UTC, ykyki commented
✅ コマンドの使い方

2022-05-15 10:03 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
>  	各$ \morph{f_i}{X_i}{Y_i} $は閉写像である.
対応しました.

2022-05-15 10:04 UTC, CptHaus commented
修正に対応しました.

2022-05-15 11:03 UTC, ykyki approved these changes

2022-05-15 11:06 UTC, ykyki commented
OK🍶

2022-05-15 11:07 UTC, merged