性質の保存の定義を追加
ykyki/extop-tex pull request #114
Opened 2022-02-18 13:22 UTC by CptHaus

## 背景・意図

- "〇〇で保たれる", "〇〇に遺伝する"という言い回しの定義をしておきたい

## したこと

- 定義: "連続写像で保たれる"
- 定義: "部分に遺伝する"
- 定義: "積で保たれる"

## してないこと

- なし

## Linked Issues

- resolve #100 

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] 出典の記載
- [ ] コマンドの使い方
- [ ] コードフォーマット

2022-02-18 14:58 UTC, ykyki commented
develop のマージをお願いします。

2022-03-13 06:54 UTC, ykyki commented
`extopy` 系のファイル削除をお願いします。

2022-03-22 14:28 UTC, ykyki requested changes
「連続写像で保たれる」などに `\indexj` を使うようにお願いします。

2022-03-22 14:28 UTC, ykyki commented on documents/catalog/theories/preservation-of-properties.tex
> +	位相空間$ X $の性質$ {\mathcal P} $が連続写像で保たれるとは,
```suggestion
	位相空間$ X $の性質$ \mathcal{P} $が連続写像で保たれるとは,
```

12行目も同様の修正お願いします。

2022-03-22 14:28 UTC, ykyki commented on documents/catalog/theories/preservation-of-properties.tex
> +	位相空間$ X $の性質$ {\mathcal P} $が連続写像で保たれるとは,
「性質」や「位相的性質」という2つの単語がこのファイルで登場していますが、違いはありますか？

なければどちらかに統一をお願いします。

2022-03-22 14:28 UTC, ykyki commented on documents/catalog/theories/preservation-of-properties.tex
> +閉写像や開写像, 商写像, 完全写像などの場合についても,
```suggestion
\end{definition}

閉写像や開写像, 商写像, 完全写像などの場合についても,
```

パラグラフが分かれるときには空行を入れるようにしましょう。

2022-03-22 14:28 UTC, ykyki commented on documents/catalog/theories/preservation-of-properties.tex
> +有限個(可算個)の積で保たれるという.
こちらはdefinition内に入れてしまっていいかも？

2022-04-02 12:39 UTC, CptHaus commented on documents/catalog/theories/preservation-of-properties.tex
> +	位相空間$ X $の性質$ {\mathcal P} $が連続写像で保たれるとは,
特に違いはないです. "位相的性質"の方を"位相空間の性質"と修正しました. ("性質"の方も位相空間??の"性質"という使い方なので整合性が取れる)

2022-04-02 12:39 UTC, CptHaus commented on documents/catalog/theories/preservation-of-properties.tex
> +閉写像や開写像, 商写像, 完全写像などの場合についても,
対応済み.

2022-04-02 12:39 UTC, CptHaus commented on documents/catalog/theories/preservation-of-properties.tex
> +有限個(可算個)の積で保たれるという.
対応済み.

2022-04-02 12:40 UTC, CptHaus commented
すべてのコメントに対応しました.
確認をお願いします.

2022-04-02 14:04 UTC, ykyki approved these changes

2022-04-02 14:04 UTC, ykyki commented
OK🍺

2022-04-02 14:07 UTC, merged