グローバルコマンド\mapsetfamily, \mapinvsetfamilyの追加
ykyki/extop-tex pull request #115
Opened 2022-02-18 13:51 UTC by CptHaus

## 背景・意図

- 集合族を写像で写すときのコマンドが欲しい

## したこと

- グローバルコマンドに\mapsetfamily, \mapinvsetfamilyを追加
- コマンドリストのPDFを更新

## Linked Issues

- resolve #81 

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] 出典の記載
- [ ] コマンドの使い方
- [ ] コードフォーマット

2022-03-21 13:08 UTC, ykyki commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\lrparen{#2}}
`\lrparen`だと`\mappt`と区別がつかないので、別の記号にしたいです。

`\lrbrack`を2つ重ねて `f[[W]]` みたいな感じするのはどうでしょうか？

単純にコマンドをネストさせるとカッコの高さがズレてしまう可能性があるかもしれないので、その場合は調整お願いします。

2022-03-21 13:08 UTC, ykyki commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\lrparen{#2}}
コマンド定義の順番を次のように合わせたいです:

`\mappt`
`\mapinvpt`
↓
`\mapset`
`\mapinvset`
↓
`\mapsetfamily`
`\mapinvsetfamily`

2022-03-22 12:26 UTC, ykyki commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\lrparen{#2}}
話し合いの結果、`\llbracket` を使うことにしました。

2022-03-22 14:16 UTC, CptHaus commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\lrparen{#2}}
\usepackage{stmaryrd}を追加してllbracket, rrbracketを用いた定義に変更しました.

2022-03-26 02:15 UTC, ykyki requested changes

2022-03-26 02:15 UTC, ykyki commented on documents/catalog/list-commands-table.tex
> +		$\mapinvsetfamily{h}{\mathscr{V}}$        & \verb|\mapinvset{h}{\mathscr{V}}|                                                & 写像$h$による集合族$\mathscr{V}$の逆像 \\
```suggestion
		$\mapset{f}{A}$                           & \verb|\mapset{f}{A}|                                                             & 写像$f$による集合$A$の順像             \\
		$\mapsetfamily{f}{\mathscr{U}}$           & \verb|\mapsetfamily{f}{\mathscr{U}}|                                                   & 写像$f$による集合族$\mathscr{U}$の順像 \\
		$\mapinvset{h}{K}$                        & \verb|\mapinvset{h}{K}|                                                          & 写像$h$による集合$K$の逆像             \\
		$\mapinvsetfamily{h}{\mathscr{V}}$        & \verb|\mapsetfamily{f}{\mathscr{U}}|                                                & 写像$h$による集合族$\mathscr{V}$の逆像 \\
```

2022-03-26 02:15 UTC, ykyki commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\mleft\llbracket{#2}\mright\rrbracket}
\mappt
\mapintpt
\mapset
\mapinvset
\mapsetfamily
\mapinvsetfamily

の順番でお願いします。

2022-03-26 02:15 UTC, ykyki commented on documents/catalog/list-commands-table.tex
> +		$\mapinvsetfamily{h}{\mathscr{V}}$        & \verb|\mapinvset{h}{\mathscr{V}}|                                                & 写像$h$による集合族$\mathscr{V}$の逆像 \\
\mappt
\mapintpt
\mapset
\mapinvset
\mapsetfamily
\mapinvsetfamily

の順番でお願いします。

2022-04-02 12:53 UTC, CptHaus commented on documents/catalog/list-commands-table.tex
> +		$\mapinvsetfamily{h}{\mathscr{V}}$        & \verb|\mapinvset{h}{\mathscr{V}}|                                                & 写像$h$による集合族$\mathscr{V}$の逆像 \\
対応済み.

2022-04-02 12:53 UTC, CptHaus commented on documents/config/global-commands.sty
> +\newcommand{\mapinvsetfamily}[2]{#1^{-1}\mleft\llbracket{#2}\mright\rrbracket}
対応済み.

2022-04-02 12:54 UTC, CptHaus commented
すべてのコメントに対応しました.
確認をお願いします.

2022-04-02 13:59 UTC, merged