連結成分に関する記述を追加
ykyki/extop-tex pull request #132
Opened 2022-04-16 09:26 UTC by CptHaus

## 背景・意図

- 連結性の章の充実を図る

## したこと

- 連結成分に関する定義と基本的な命題について記述

## 参考資料

- Engelking, 森田

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] 出典の記載
- [ ] コマンドの使い方
- [ ] コードフォーマット

2022-04-16 10:32 UTC, ykyki requested changes
checked:

- コマンドの使い方

2022-04-16 10:32 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	\setcomp{C \in \mathcal{P}(X)}{x \in C, C\mbox{は連結集合}} $
微妙なところですが、定義は強調しておきたいのでディスプレイ数式に変更にお願いします。

それと冪集合は `\pow` を使うようにお願いします。

2022-04-16 10:32 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	\bigcap \setcomp{Q \in \mathcal{P}(X)}{x \in Q, Q\mbox{は開閉集合}} $
微妙なところですが、定義は強調しておきたいのでディスプレイ数式に変更にお願いします。

それと冪集合は `\pow` を使うようにお願いします。

2022-04-16 10:32 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	また, $ C(y) $についてもその最大性から$ C(X) \subset C(Y) $が成り立つので
```suggestion
	また, $ C(y) $についてもその最大性から$ C(x) \subset C(y) $が成り立つので
```

2022-04-16 11:21 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	\setcomp{C \in \mathcal{P}(X)}{x \in C, C\mbox{は連結集合}} $
対応済み.

2022-04-16 11:22 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	\bigcap \setcomp{Q \in \mathcal{P}(X)}{x \in Q, Q\mbox{は開閉集合}} $
対応済み.

2022-04-16 11:23 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	また, $ C(y) $についてもその最大性から$ C(X) \subset C(Y) $が成り立つので
対応済み.

2022-04-23 10:16 UTC, ykyki commented
OK: コマンドの使い方

2022-04-23 10:18 UTC, ykyki commented
OK: コードフォーマット

2022-04-23 10:18 UTC, ykyki approved these changes

2022-04-23 10:19 UTC, merged