シグマ連結性に関する記述を連結性のファイルに移動
ykyki/extop-tex pull request #139
Opened 2022-05-15 09:26 UTC by CptHaus

## 背景・意図

- 連結性の節に連結成分の話題が出てくるので, シグマ連結もそこでまとめて扱いたい

## したこと

- sigma-connected-spaces.texの内容をconnected_spaces.texに移動
- 移動に際して記述と集学的内容の微修正

## してないこと

- sigma-connected-spaces.texの削除.

## 参考資料

- Engelking

## Linked Issues

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] 出典の記載
- [ ] コマンドの使い方・コードフォーマット

2022-06-03 12:38 UTC, ykyki requested changes

2022-06-03 12:38 UTC, ykyki commented on documents/catalog/theories/sigma-connected-spaces.tex
> +	それら閉集合の中で少なくとも1つが$ X $と等しくなることである.
$\sigma$-連結空間のセクションと連結空間のセクションで重複した内容があります。
どちらか一方にまとめるようお願いします。

2022-06-10 14:00 UTC, CptHaus commented on documents/catalog/theories/sigma-connected-spaces.tex
> +	それら閉集合の中で少なくとも1つが$ X $と等しくなることである.
σ-連結空間のセクションの内容を連結空間のセクションにコピーしているので重複しているのは問題ありません.
連結空間にコピーした内容で問題なければ, σ-連結空間のセクションファイルは削除する予定でした.

2022-06-10 14:39 UTC, ykyki commented on documents/catalog/theories/sigma-connected-spaces.tex
> +	それら閉集合の中で少なくとも1つが$ X $と等しくなることである.
OK

2022-06-25 05:25 UTC, ykyki commented
GitHub Action が失敗している: https://github.com/ykyki/extop-tex/runs/7051776711?check_suite_focus=true

エラーメッセージ抜粋:
```
------------
Running 'dvipdfmx  -g 1.5pt -o "chapter-connectedness.pdf" "chapter-connectedness.dvi"'
------------
][2][3][4][5][6][7][8]
129362 bytes written
Latexmk: Undoing directory change
----- ----- ----- ----- ----- ----- ----- ----- 
Build: /__w/extop-tex/extop-tex/temp/connected-spaces-review-0c6dc87.pdf
/__w/extop-tex/extop-tex
chapter-connectedness.dvi -> chapter-connectedness.pdf
[1][2][3][4][5][6][7][8][9]
136508 bytes written
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 9 citation(s)
Collected warning summary (may duplicate other messages):
  biber chapter-connectedness: Could not find bib file for 'chapter-connectedness'
Latexmk: Undoing directory change
----- ----- ----- ----- ----- ----- ----- ----- 
```

→ Compare アクションあるいはその処理中で使用しているシェルスクリプトを修正する必要あり。

2022-06-25 05:41 UTC, ykyki commented
↑のステータス check が通り次第マージします

2022-06-25 05:54 UTC, ykyki approved these changes

2022-07-02 08:19 UTC, merged