距離空間に関して記述するファイルを追加
ykyki/extop-tex pull request #146
Opened 2022-06-10 13:56 UTC by CptHaus

## 背景・意図

- 距離空間に関する記述を行うファイルが準備されていなかったので追加

## したこと

- 基本的な定義の記述
- いくつかの命題を列挙
- 距離化可能性が積(可算)で保たれることの証明

## してないこと

- チャプターファイルへのimport

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] 出典の記載
- [ ] コマンドの使い方・コードフォーマット

2022-06-25 06:11 UTC, ykyki commented
「未分類」というチャプターを第I部の最後に追加し、今回作成したセクションはそこに追加しましょう。

修正後のセクション構造のイメージ:

第I部: 位相空間論
第x章: 未分類
x.y: （命名おまかせします）
x.y.1: 距離空間

2022-07-02 09:04 UTC, ykyki requested changes
数学的内容に関するチェック完了

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ (X, d) $を\indexjj{きょりくうかん}{離化空間}{metric space}といい,
```suggestion
	$ (X, d) $を\indexjj{きょりくうかん}{距離空間}{metric space}といい,
```

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	で定義される$ \topball{x}{\varepsilon} $を$ x $の
```suggestion
	で定義される部分集合$ \topball{x}{\varepsilon} $を$ x $の
```

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	\topball{x}{\varepsilon} \subset U \mbox{を満たす.}} \]
```suggestion
	\topball{x}{\varepsilon} \subset U \mbox{を満たす}} \]
```

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +上のように定義される$ \mathcal{O}_d $が位相の公理を満たすことは容易に確かめられる.
```suggestion
上のように定義される$ \mathcal{O}_d $が開集合族の公理を満たすことは容易に確かめられる.
```

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ d(x, z) \leq d(x, y) + d(y, z) < d(x, y) + \delta < \varepsilon $が成り立つ.
長い数式なのでディスプレイ数式に変更を願いします。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ y \neq x $のときある$ \delta > 0 $であって$ \delta < \varepsilon - d(x,y) $を満たすものが存在する.
場合分けしていますが、 $y = x$ の場合でも議論が成り立つので、不要です。
場合分けの削除お願いします。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +			\subset B(x, \mappt{f}{x}).\]
```suggestion
			\subset B(f(x), \epsilon).\]
```

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ X, Y $を, それぞれの距離$ d_X, d_Y $から定まる位相をもつ位相空間とみなすとき,
ここの断りは、注意が上述されているので、不要です。
削除お願いします。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	よって, $ U = \bigcup_{x \in U} B(x, \varepsilon) $より$ U \in \mathcal{O}_{d^{(\infty)}} $が成り立つ.
```suggestion
	よって, $ U \in \mathcal{O}_{d^{(\infty)}} $が成り立つ.
```

距離関数が定める位相の定義を確認するだけなので、合併に関する記述は不要。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ B(x, \varepsilon) \subset \prod_{i=0}^n B_i(x_i, \varepsilon) \subset U $が成り立つ.
$$B(x, \varepsilon) = \prod_{i=0}^n B_i(x_i, \varepsilon)$$
これを言い切ってしまった方が議論の見通しがよくなりそうです。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ \mathcal{O}_X \subset \mathcal{O}_d $が成り立つ.
補足文として、「射影 $p_n$ が連続である」という主張を、上述の命題を cref しつつ挟んでおきたいです。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ U_n \defeq \setcomp{b \in X_n}{d'_n(x_n, b) < \frac{\varepsilon}{4}} $と定める.
ただの開球なので $U_n = B(x_n, \epsilon / 4) $ みたいな書き方でいいかと。 (`\topball` コマンドを使いつつ)

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ \sum_{n=k+1}^\infty 2^{-n} d'_n(x_n, y_n) \geq \sum_{n=k+1}^\infty 2^{-n}
込み入っているのでディスプレイ数式に直したいです。

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ \sum_{n=k+1}^\infty 2^{-n} d'_n(x_n, y_n) \geq \sum_{n=k+1}^\infty 2^{-n}
2つめの数式内の `\geq` → `\leq`

2022-07-02 09:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ \morph{f}{X}{Y} $を距離化可能空間$ X $から位相空間$ Y $への開閉写像とする.
開閉写像 = 開写像 かつ 閉写像？ (定義がない)

2022-07-02 09:06 UTC, ykyki commented
✅  文章の記述位置

2022-07-23 08:03 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ \morph{f}{X}{Y} $を距離化可能空間$ X $から位相空間$ Y $への開閉写像とする.
対応しました

2022-07-23 08:03 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ \sum_{n=k+1}^\infty 2^{-n} d'_n(x_n, y_n) \geq \sum_{n=k+1}^\infty 2^{-n}
対応しました

2022-07-23 08:03 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ U_n \defeq \setcomp{b \in X_n}{d'_n(x_n, b) < \frac{\varepsilon}{4}} $と定める.
この場合\topballを使ってしまうとどの距離空間における開球かがわかりにくくなくなるのでこのように書いていました.

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ \mathcal{O}_X \subset \mathcal{O}_d $が成り立つ.
\cref はどの命題を想定していますか?

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ B(x, \varepsilon) \subset \prod_{i=0}^n B_i(x_i, \varepsilon) \subset U $が成り立つ.
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	よって, $ U = \bigcup_{x \in U} B(x, \varepsilon) $より$ U \in \mathcal{O}_{d^{(\infty)}} $が成り立つ.
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ X, Y $を, それぞれの距離$ d_X, d_Y $から定まる位相をもつ位相空間とみなすとき,
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +			\subset B(x, \mappt{f}{x}).\]
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ y \neq x $のときある$ \delta > 0 $であって$ \delta < \varepsilon - d(x,y) $を満たすものが存在する.
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ d(x, z) \leq d(x, y) + d(y, z) < d(x, y) + \delta < \varepsilon $が成り立つ.
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +上のように定義される$ \mathcal{O}_d $が位相の公理を満たすことは容易に確かめられる.
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	\topball{x}{\varepsilon} \subset U \mbox{を満たす.}} \]
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	で定義される$ \topball{x}{\varepsilon} $を$ x $の
対応しました

2022-07-23 08:04 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ (X, d) $を\indexjj{きょりくうかん}{離化空間}{metric space}といい,
対応しました

2022-07-23 10:07 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ \mathcal{O}_X \subset \mathcal{O}_d $が成り立つ.
67行目前後の、所謂 `\epsilon-\delta` 論法による連続性の特徴づけ指している想定（のはず…）

2022-07-23 10:07 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ U_n \defeq \setcomp{b \in X_n}{d'_n(x_n, b) < \frac{\varepsilon}{4}} $と定める.
話し合いの結果 `\topballsf` をグローバル定義する方針にしました。

2022-08-19 12:48 UTC, ykyki commented
↑のコメントの対応お願いします 🙇 : https://github.com/ykyki/extop-tex/pull/146#discussion_r928105457

2022-08-19 12:49 UTC, ykyki commented
✅  数学的な内容

2022-08-19 12:57 UTC, ykyki commented
次のエラーでビルド失敗が発生しているので、対応お願いします: 

```
././theories/metric-spaces.tex:9: LaTeX Error: Command \topbd already defined.
               Or name \end... illegal, see p.192 of the manual.
```

2022-08-19 13:29 UTC, ykyki commented
`build.sh` が意図しない挙動をしていたので、動作確認を兼ねてこの場で修正をプッシュしました。

2022-08-19 13:31 UTC, ykyki commented
キチンと失敗で終了するようになり、ログにも出るようになったのでヨシ
https://github.com/ykyki/extop-tex/runs/7919100930

2022-08-19 13:52 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ U_n \defeq \setcomp{b \in X_n}{d'_n(x_n, b) < \frac{\varepsilon}{4}} $と定める.
グローバルコマンドに追加して本文にも反映させました

2022-09-02 12:04 UTC, ykyki requested changes
チェックしました。

- 出典の記載
- コマンドの使い方・コードフォーマット

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +\end{proposition}
```suggestion
	\end{enumerate}
	\qed
\end{proposition}
```

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +\end{proposition}
```suggestion
	$ d, d' $の定める位相は一致する.
	\qed
\end{proposition}
```

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +\begin{theorem}[Hanai-Morita-Stone Theorem]
出典か参考文献を追加

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	集合$ X $と写像$ d \colon X \times X \to \R $の組$ (X, d) $について次の4条件が成り立つとき,
`\morph`を使う

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +\label{sec:metric-spaces}
`\begin{source}` で出典追加をお願いします。

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	\indexjj{イプシロンきんぼう}{$\varepsilon$近傍}{epsilon neighborhood}または
```suggestion
	\indexjj{イプシロンきんぼう}{$\varepsilon$-近傍}{epsilon neighborhood}または
```

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	写像$ f \colon X \to Y $について次は同値である.
`\morph`

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ d'_n(a, b) = \min\{d_n(a,b), 1\} $と定める.
`\lrbrace`

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	各$ n \in \N $について, $ d'_n \colon X_n \times X_n \to \R $を
`\morphto`

2022-09-02 12:04 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
> +	$ d \colon X \times X \to \R $を$ d(x, y) = \sum_{n \in \N}
`\morph`

2022-09-09 11:41 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +\end{proposition}
対応済み

2022-09-09 11:41 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +\end{proposition}
対応済み

2022-09-09 11:43 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +\begin{theorem}[Hanai-Morita-Stone Theorem]
対応済み

2022-09-09 11:46 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	集合$ X $と写像$ d \colon X \times X \to \R $の組$ (X, d) $について次の4条件が成り立つとき,
対応済み

2022-09-09 11:47 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +\label{sec:metric-spaces}
対応済み

2022-09-09 11:57 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	\indexjj{イプシロンきんぼう}{$\varepsilon$近傍}{epsilon neighborhood}または
対応済み

2022-09-09 11:57 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	写像$ f \colon X \to Y $について次は同値である.
対応済み

2022-09-09 11:57 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ d'_n(a, b) = \min\{d_n(a,b), 1\} $と定める.
対応済み

2022-09-09 11:57 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	各$ n \in \N $について, $ d'_n \colon X_n \times X_n \to \R $を
対応済み

2022-09-09 11:57 UTC, CptHaus commented on documents/catalog/theories/metric-spaces.tex
> +	$ d \colon X \times X \to \R $を$ d(x, y) = \sum_{n \in \N}
対応済み

2022-09-09 12:10 UTC, CptHaus commented
コミットコメントが変になってしまいましたが, 出典記載とコマンドの修正を完了しています.

2022-09-09 13:21 UTC, ykyki commented on documents/catalog/theories/metric-spaces.tex
>  	$ d' \colon X \times X \to \R $を$ d'(x, y) \defeq \min \lrbrace{\varepsilon,
`\morph`

2022-09-10 04:54 UTC, ykyki approved these changes

2022-10-08 11:04 UTC, merged