問題1.5.Cの証明とその際に用いる命題の記述・証明
ykyki/extop-tex pull request #182
Opened 2022-11-04 12:36 UTC by CptHaus

## したこと

- 問題1.5.Cの証明
- Hausdorff性に関する命題(h00001)の記述・証明

## プルリク提出前: 確認事項

- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

## リバイズ進行状態

- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] コマンドの使い方・コードフォーマット

2022-11-25 12:12 UTC, ykyki requested changes
コメントした部分が修正されればOKです。

2022-11-25 12:12 UTC, ykyki commented on documents/catalog/theories/Hausdorff-spaces.tex
> +	\( f, g \colon X \to Y \)を連続写像とする.
`\morph`を使う。

2022-11-25 12:12 UTC, ykyki commented on documents/engelking/1-5-C-proof.tex
> +\documentclass[uplatex, dvipdfmx, a4paper, 12pt, class=jsarticle, crop=false]{standalone}
`engelking/list.tex`に追加

2022-12-04 11:16 UTC, CptHaus commented on documents/catalog/theories/Hausdorff-spaces.tex
> +	\( f, g \colon X \to Y \)を連続写像とする.
対応しました.

2022-12-04 11:16 UTC, CptHaus commented on documents/engelking/1-5-C-proof.tex
> +\documentclass[uplatex, dvipdfmx, a4paper, 12pt, class=jsarticle, crop=false]{standalone}
対応しました.

2022-12-17 11:29 UTC, ykyki commented on documents/engelking/1-5-C-proof.tex
> +\documentclass[uplatex, dvipdfmx, a4paper, 12pt, class=jsarticle, crop=false]{standalone}
こちらの対応もお願いします。

2022-12-23 11:50 UTC, CptHaus commented on documents/engelking/1-5-C-proof.tex
> +\documentclass[uplatex, dvipdfmx, a4paper, 12pt, class=jsarticle, crop=false]{standalone}
対応しました.

2022-12-26 15:12 UTC, ykyki approved these changes
OK

2022-12-26 15:12 UTC, merged