問題1.5.Dの記述を追加
ykyki/extop-tex pull request #186
Opened 2022-11-25 12:22 UTC by CptHaus

2022-12-17 11:39 UTC, ykyki commented on documents/engelking/1-5-D-problem.tex
> +		\( \cardinality{X} \leq \lrbrack{\topdensity{X}}^{\topcharacter{X}} \)
`\lrbrack`は不要かと

2022-12-17 11:39 UTC, ykyki commented on documents/engelking/1-5-D-problem.tex
> +\begin{problem}[1.5.D]\label{eng-1-5-D-problem}
`engelking/list.tex` に追加をお願いします。

2022-12-23 11:56 UTC, CptHaus commented on documents/engelking/1-5-D-problem.tex
> +		\( \cardinality{X} \leq \lrbrack{\topdensity{X}}^{\topcharacter{X}} \)
engelkingの方は括弧があったので合わせてましたが消しました.

2022-12-23 11:59 UTC, CptHaus commented on documents/engelking/1-5-D-problem.tex
> +\begin{problem}[1.5.D]\label{eng-1-5-D-problem}
対応しました

2023-01-03 11:25 UTC, ykyki commented
コンフリクト解消おねがいします。

2023-01-09 11:49 UTC, ykyki requested changes

2023-01-09 11:49 UTC, ykyki commented on documents/engelking/list.tex
> +	\import{./}{1-5-D-problem}
- importの重複
- インデントの統一 (Tabインデント)

の修正をお願いします。

2023-01-20 11:52 UTC, CptHaus commented on documents/engelking/list.tex
> +	\import{./}{1-5-D-problem}
対応しました.

2023-01-29 11:04 UTC, ykyki approved these changes

2023-01-29 11:07 UTC, merged