Feature/20221204/characterization of t4
ykyki/extop-tex pull request #188
Opened 2022-12-09 13:19 UTC by CptHaus

** したこと **
- T4空間の特徴づけ定理の記述と証明
- T3なLindelof空間がT4であることの証明

** 確認事項 **
- [ ] 変更範囲の再確認
- [ ] Reviewers, Assignees, Labels, ...の項目設定
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] このプルリクのプレビュー

** リバイズ進行状態 **
- [ ] 文章の記述位置
- [ ] 数学的な内容
- [ ] 誤植や言葉使いなど文章の細部
- [ ] コマンドの使い方・コードフォーマット

2022-12-17 12:00 UTC, ykyki reviewed
レビューしました。

2022-12-17 12:00 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +\begin{theorem}
出典を記載

2022-12-17 12:00 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +\begin{theorem}
この定理のひとつ前に、`\label{prop:A property equivalent to regularity}`と似た形の、閉集合と開集合を用いた正規性の特徴付けを述べておきたいです。

2022-12-17 12:00 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +	\( F, G \)を互いに交わらない閉集合とする.
閉集合を表す記号として`G`を用いるのは避けたい。ほとんどの場合で開集合を表す記号として使っているので。

2022-12-17 12:00 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +	\topT{1}位相空間\( X \)が \topT{4} であるための必要十分条件は,
`\topT{1}`の仮定は使ってなさそうなので、正規性の特徴付けとして使えそう？

2022-12-23 12:37 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +\begin{theorem}
出典追加しました.
正規性の特徴付の命題を追加しました.

2022-12-23 12:38 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +	\( F, G \)を互いに交わらない閉集合とする.
F'に変更しました.

2022-12-23 12:39 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +	\topT{1}位相空間\( X \)が \topT{4} であるための必要十分条件は,
T1なくても大丈夫そうな証明なので正規性の特徴付として修正しました.

2023-01-09 12:04 UTC, ykyki requested changes

2023-01-09 12:04 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +	\topT{3} 空間\( X \)が \Lindelof であるならば \topT{4} 空間である.
前の定理の仮定が $\rm T_4$ → 正規性に変わったので、こっちも正則性に修正できそうです。

2023-01-09 12:04 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +\end{proposition}
```suggestion
	を満たすものが存在することは同値である.
	\qed
\end{proposition}
```
自明として証明を省略するので `\qed` を追加

2023-01-09 12:04 UTC, ykyki commented on documents/catalog/theories/normal-spaces.tex
> +	必要性は明らかなので十分性を示す.
せっかくなら命題`\label{t400002}`を使っていることを明記しておきたいです。

2023-01-09 12:05 UTC, ykyki commented
上記コメントが対応されればマージします。

2023-01-20 12:00 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +	必要性は明らかなので十分性を示す.
対応しました

2023-01-20 12:00 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +\end{proposition}
対応しました

2023-01-20 12:00 UTC, CptHaus commented on documents/catalog/theories/normal-spaces.tex
> +	\topT{3} 空間\( X \)が \Lindelof であるならば \topT{4} 空間である.
対応しました

2023-01-29 11:53 UTC, ykyki approved these changes
OK 🧀

2023-01-29 11:55 UTC, merged