Feature/047 import 046
ykyki/extop-tex pull request #29
Opened 2021-08-31 00:42 UTC by CptHaus

前のプルリクを閉じてしまったので再度プルリクを出します.

2021-09-05 06:14 UTC, ykyki requested changes
確認しました。いくつか細かな修正を再度お願いします🙇

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	\indexjj{かさんめたこんぱくと}{可算メタコンパクト}{countable metacompact}であるという.
```suggestion
	\indexjj{かさんめたこんぱくと}{可算メタコンパクト}{countablely metacompact}であるという.
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	\indexjj{かさんおるそこんぱくと}{可算オルソコンパクト}{countable orthocompact}であるという.
```suggestion
	\indexjj{かさんおるそこんぱくと}{可算オルソコンパクト}{countablely orthocompact}であるという.
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +\end{proposition}
この書き方だと定義っぽく見えてしまう。

同値であるという書き方に直して、同値性の証明は参考文献を追加して cite する。

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +\end{proposition}
簡単な証明を省略するときには `\qed` を付けて、省略することを明示する。

```suggestion
\begin{proposition}
	\label{prop: Subspace of a P-space is also a P-space}
	P空間の部分空間(非交和, 有限個の積, \topT{1}な商空間)もまたP空間である.
	\qed
\end{proposition}
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +\end{proposition}
命題と証明の場所が離れてしまっている。

証明に必要な定義や補題を用意しますよ、という宣言文が一言挟んであると戸惑わなくなってありがたい。

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	点有限な開被覆$ \{V_s\}_{s \in S} $が存在して任意の$ s \in S $について$ V_s \subset U_s $が成り立つ.
`\setfamily` コマンドを使う。もしくは波括弧ではなく丸括弧で。

```suggestion
	メタコンパクト空間$ X $の添字付けられた開被覆$ \setfamily{U_s}{s \in S} $に対して,
	点有限な開被覆$ \setfamily{V_s}{s \in S} $が存在して任意の$ s \in S $について$ V_s \subset U_s $が成り立つ.
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	\cref{prop: Every sigma-point-finite open covering of the closed image of a MetaCpt space
ひとまずWIPを付けておいてください。後で読みます。

```suggestion
\begin{proof}
	(WIP)
	\cref{prop: Every sigma-point-finite open covering of the closed image of a MetaCpt space 
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	$ X $の有限部分集合$ A_y $が存在する.
```suggestion
	$ X $の有限部分集合$ A_y $が存在して$ \setcomp{V_{(x, y)}}{x \in A_y} $が$ X $の開被覆となる.
 
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	位相空間$ X $の開被覆$ \mathscr{U} $が\indexjj{きやく}{既約}{irreducible}であるとは,
```suggestion
	位相空間$ X $の被覆$ \mathscr{U} $が\indexjj{きやく}{既約}{irreducible}であるとは, 
```

2021-09-05 06:14 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +	$ (F_n)_{n \in \N} $が単調増加であることから$ y \in \mathscr{W}_i $なる
```suggestion
	$ (F_n)_{n \in \N} $が単調増加であることから$ y \in \bigcup \mathscr{W}_i $となる
```

2021-09-17 13:30 UTC, CptHaus commented on documents/main/theories/paracompact-like-properties.tex
> +\end{proposition}
この命題て以降で参照されてましたっけ. 主張が面白いので載せていただけのような.(参照論文の引用は付けました)
命題0.1.10は主張と証明が離れているのでそのことの注意書きをしました.

2021-09-17 13:34 UTC, ykyki commented on documents/main/theories/paracompact-like-properties.tex
> +\end{proposition}
他の部分で参照されているところはなかったはず。Worellの定理で使っていることがなければ。

2021-09-17 14:46 UTC, merged