073 connected spaces
ykyki/extop-tex pull request #72
Opened 2021-10-16 06:07 UTC by CptHaus

## 詳細

- 連結性の定義と基本的な命題及びその証明の追記

## したこと

- 定義
- 連結性の特徴付け
- 連続写像で保たれること
- 弧状連結ならば連結であること
- 連結部分集合族の和が連結になる条件
- 連結部分集合の閉包が連結であること
- 連結空間の積が連結であること

## してないこと

- 連結空間の積が連結であることの証明

## 連絡事項

- なし

## 参考資料

- セクション冒頭に記載

## Linked Issues

- なし

## 確認事項

- [x] 変更箇所の動作確認・表示確認
- [x] レビュアー等の設定
- [x] このプルリクエストのプレビュー

2021-10-16 07:00 UTC, ykyki commented
「離散空間」という用語は未定義だった気がするので、追記をお願いします。

2021-10-23 06:50 UTC, ykyki commented
空集合は連結でも弧状連結でもないことにしました。（口頭相談）
そのため、現在の弧状連結の定義の修正をお願いします。

2021-10-30 05:00 UTC, ykyki requested changes
朱入れした PDF ファイルは別途送付します。

2021-10-30 05:00 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +				a_n = a_{n-1}, b_n = \frac{a_{n-1} + b_{n-1}}{2} & (\gamma\left(\frac{a_{n-1} + b_{n-1}}{2}\right) \in F_1).
こうした分岐した式の書き方はまだ統一されていません。
個人的には現状、条件式を囲む括弧はなくていいと考えています。
`documents/catalog/theories/quotient-space-by-one-point-squashing.tex` 56行目あたりの書き方を参考に

2021-10-30 05:01 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	\WIP
```suggestion
	\WIP.
```

2021-10-30 05:43 UTC, ykyki reviewed
コードチェックを途中までしました。

2021-10-30 05:43 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	位相空間$ X $が\indexjj{れんけつ}{連結}{connected}であるとは, $ X $が空でなく$ X $を有限個の互いに交わらない開集合の合併で表したとき常に,
空でないことの条件は不要です。
X が空の場合には、0個の開集合の合併を考えたときに条件を満たしません。

2021-10-30 05:43 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
>  		\qed
証明を書いたので、こちらの `\qed` は外してしまいましょう

2021-10-30 05:43 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ \setcomp{a_n}{n \in \N} \subset \gamma^{-1}[F_0], \setcomp{b_n}{n \in \N} \subset \gamma^{-1}[F_1] $であることから,
集合の逆像は `\mapinvset` コマンドを使いましょう。
(list-command-table.pdf を参考に)

2021-10-30 05:43 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	位相空間$ X $の任意の2点についてそれらを含む同一の連結部分集合が存在するとき$ X $は連結である.
Xが空でないという条件が必要だった。見逃してた…。

2021-11-13 04:09 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ F_0, F_1 $は閉集合なので$\topcl{\mapinvset{\gamma}{F_0}} = \mapinvset{\gamma}{F_0}, topcl{\mapinvset{\gamma}{F_1}} = \mapinvset{\gamma}{F_1} $であり,
```suggestion
	$ F_0, F_1 $は閉集合なので$\topcl{\mapinvset{\gamma}{F_0}} = \mapinvset{\gamma}{F_0}, \topcl{\mapinvset{\gamma}{F_1}} = \mapinvset{\gamma}{F_1} $であり,
```

2021-11-13 04:32 UTC, CptHaus commented
\mappt, \mapset, \mapinvpt, \mapinvset, \morphを使用するように修正

2021-11-20 10:52 UTC, ykyki commented
@CptHaus 細かな修正を行いました。問題なさそうであればマージお願いします🙇

2021-11-20 12:43 UTC, merged