Feature/079 closed maps
ykyki/extop-tex pull request #84
Opened 2021-11-20 12:52 UTC by CptHaus

## 詳細

-基本的な命題と証明の記述

## したこと

- なし

## してないこと

- 写像の積が閉になる場合に各写像が閉になることの証明

## 連絡事項

- なし

## 参考資料

- Engelkingがメイン

## Linked Issues

- なし

## 確認事項

- [ ] 変更箇所の動作確認・表示確認
- [ ] レビュアー等の設定
- [ ] このプルリクエストのプレビュー

2021-11-27 06:00 UTC, ykyki commented
## レビュー進行状態

1. [ ] 文章の配置場所やレイアウト
2. [ ] 数学的な内容
3. [ ] 出典の記載
4. [ ] 誤植や言葉使いなど文章の細部
5. [ ] コマンドの使い方
6. [ ] ソースコードのフォーマット

2021-11-27 06:33 UTC, ykyki commented
命題に Engelking  からの出典を付けてありますが、文献名だけでなく定理番号も記載をお願いします。
Engelking という表記だけだと、後から確認するときに当該箇所を探すのが大変になりそうなので。

2021-11-27 06:46 UTC, ykyki commented
こちらの勘違いでした。
セクションのファイルを単体でproductレイアウトで生成すると定理番号が表示されなくなっていたようです。

2021-11-27 06:48 UTC, ykyki commented
「連続写像の積が塀写像なら各成分の連続写像も閉である」命題の出典記載をお願いします。

2021-12-11 08:50 UTC, ykyki requested changes
以下の観点でチェックを終えました:

- 出典の記載
- 誤植や言葉使いなど文章の細部

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +        \item 任意の集合$ A \subset Y $と$ \mapinvset{f}{A} \subset U $なる$ X $の任意の開集合$ U $に対して
インデントは4スペースではなくタブでお願いします。
このファイル中の既存の部分にも要変更箇所がありますが、追加で対応をお願いします。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
>  	$ X $の任意の閉写像$ F $に対して$ \mapset{f}{F} $が$ Y $の閉集合であるとき,
閉写像の定義で`\indexjj`を使うように変更対応をお願いします。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    (2)ならば(3)が成り立つことは$ A $が特に一点集合の場合を考えれば良い.
パラグラフを区切るために前に改行を入れてください。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    (3)ならば(1)を示す. $ F \subset  X $を閉集合とする.
パラグラフを区切るために前に改行を入れてください。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    このとき, 合成写像$ \morph{g \circ f}{X}{Z} $も閉写像である.
```suggestion
    このとき, 合成写像$ \morph{g \compro f}{X}{Z} $も閉写像である.
```

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ y \in \topcl \mapset{f}{F} $なので$ V \cap \mapset{f}{F} \neq \emptyset $であることから,
ここで一度文を区切りましょう。（一文はできるだけに短く簡潔にする原則）

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    2つの閉写像の積写像も閉写像になるとは限らない. その例は\WIP.
```suggestion
    2つの閉写像の積写像も閉写像になるとは限らない.
    \WIP.
```

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ Y $のコンパクト集合である. \Hausdorff 空間のコンパクト部分集合は閉集合なので
```suggestion
    $ Y $のコンパクト集合である.
    \Hausdorff 空間のコンパクト部分集合は閉集合なので
```

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ Y $のコンパクト集合である. \Hausdorff 空間のコンパクト部分集合は閉集合なので
一応非自明な事実を用いているので定理参照を付けておきましょう。
「Hausdorff空間はKC-closedである」といった命題があればそちらに。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ X $を位相空間, $ Y $をk空間とし, $ \morph{f}{X}{Y} $を連続写像とする.
#88 で対応する。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ \morph{g}{f|_{\mapinvset{f}{F}}}{F} \semicolon x \mapsto \mappt{f}{x} $が閉写像になることである.
```suggestion
    $ \morph{f|_{\mapinvset{f}{F}}{\mapinvset{f}{F}}{F} \semicolon x \mapsto \mappt{f}{x} $が閉写像になることである.
```

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +    $ X $を可算コンパクト空間とし, $ Y $を列型空間とする. このとき, 射影$ \morph{p}{X}{Y} $は閉写像である.
射影pのドメインは積空間に。

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/continuous-maps.tex
> +	このとき$ f $が点$ a $で\indexjj{れんぞく}{連続}{continuous}であるとは, $ \mappt{f}{a} $の任意の近傍$ V $に対して$ a $のある近傍$ U $が存在して$ \mapset{f}{U} \subset V $となることである.
```suggestion
	このとき$ f $が点$ a $で\indexjj{れんぞく}{連続}{continuous}であるとは, $ f(a) $の任意の近傍$ V $に対して$ a $のある近傍$ U $が存在して$ \mapset{f}{U} \subset V $となることである.
```

2021-12-11 08:50 UTC, ykyki commented on documents/catalog/theories/continuous-maps.tex
> +	$ X, Y $を位相空間, $ \morph{f}{X}{Y} $を写像とする.
重複しているので、この定義の削除をお願いします。

このファイルの改修は後日: #89

2021-12-18 04:35 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +        \item 任意の集合$ A \subset Y $と$ \mapinvset{f}{A} \subset U $なる$ X $の任意の開集合$ U $に対して
対応済

2021-12-18 04:39 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
>  	$ X $の任意の閉写像$ F $に対して$ \mapset{f}{F} $が$ Y $の閉集合であるとき,
対応済

2021-12-18 04:39 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    (2)ならば(3)が成り立つことは$ A $が特に一点集合の場合を考えれば良い.
対応済

2021-12-18 04:40 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    (3)ならば(1)を示す. $ F \subset  X $を閉集合とする.
対応済

2021-12-18 04:40 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    このとき, 合成写像$ \morph{g \circ f}{X}{Z} $も閉写像である.
対応済

2021-12-18 04:42 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    $ y \in \topcl \mapset{f}{F} $なので$ V \cap \mapset{f}{F} \neq \emptyset $であることから,
対応済

2021-12-18 04:42 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    2つの閉写像の積写像も閉写像になるとは限らない. その例は\WIP.
対応済

2021-12-18 04:46 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    $ Y $のコンパクト集合である. \Hausdorff 空間のコンパクト部分集合は閉集合なので
対応済

2021-12-18 04:49 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    $ \morph{g}{f|_{\mapinvset{f}{F}}}{F} \semicolon x \mapsto \mappt{f}{x} $が閉写像になることである.
対応済

2021-12-18 04:50 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +    $ X $を可算コンパクト空間とし, $ Y $を列型空間とする. このとき, 射影$ \morph{p}{X}{Y} $は閉写像である.
対応済

2021-12-18 04:53 UTC, CptHaus commented on documents/catalog/theories/continuous-maps.tex
> +	このとき$ f $が点$ a $で\indexjj{れんぞく}{連続}{continuous}であるとは, $ \mappt{f}{a} $の任意の近傍$ V $に対して$ a $のある近傍$ U $が存在して$ \mapset{f}{U} \subset V $となることである.
対応済

2021-12-18 04:54 UTC, CptHaus commented on documents/catalog/theories/continuous-maps.tex
> +	$ X, Y $を位相空間, $ \morph{f}{X}{Y} $を写像とする.
どの定義と重複していますか?

2021-12-18 05:01 UTC, ykyki commented on documents/catalog/theories/continuous-maps.tex
> +	$ X, Y $を位相空間, $ \morph{f}{X}{Y} $を写像とする.
ふたつ上に書かれている定義。連続写像の定義が2つある状態になっています。

2021-12-18 05:16 UTC, CptHaus commented on documents/catalog/theories/continuous-maps.tex
> +	$ X, Y $を位相空間, $ \morph{f}{X}{Y} $を写像とする.
2つ目の写像の連続性の定義を削除して, 1つ目の定義に, "任意の点aについて連続であるときfは連続写像であるという"という記述を追加して対応

2021-12-25 04:43 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	$ X $を位相空間, $ Y $をk空間とし, $ \morph{f}{X}{Y} $を連続写像とする.
```suggestion
	$ X $を位相空間, $ Y $をk-空間とし, $ \morph{f}{X}{Y} $を連続写像とする.
```

#94 で表記方法を決めました。

2021-12-25 04:58 UTC, ykyki commented on documents/catalog/theories/continuous-maps.tex
>  \end{proposition}
今回のPRには直接は関係ない部分ですが、重複になっているので削除をお願いします。

2021-12-25 05:07 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +\end{proposition}
この箇所が原因でビルドエラーが発生しているようなので、修正お願いします。

また https://github.com/ykyki/extop-tex/commit/5d9a2cf656f39d94f70c93034cb5c4f652728528 がdevelopにマージ済みなので、`\morphto` を使用してください。

2021-12-25 05:21 UTC, ykyki requested changes
以下の観点でチェックを終えました:

-  コマンドの使い方
- ソースコードのフォーマット

2021-12-25 05:21 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +	\semicolon (x_i)_{i \in I} \mapsto (\mappt{f_i}{x_i})_{i \in I} $が閉写像ならば
こちらも`\morphto`に置換してください

2021-12-25 05:21 UTC, ykyki commented on documents/catalog/theories/closed-maps.tex
> +
余分な空行

2022-01-09 08:33 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	$ X $を位相空間, $ Y $をk空間とし, $ \morph{f}{X}{Y} $を連続写像とする.
対応済み

2022-01-09 08:33 UTC, CptHaus commented on documents/catalog/theories/continuous-maps.tex
>  \end{proposition}
対応済み

2022-01-09 08:33 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +\end{proposition}
対応済み

2022-01-09 08:37 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +	\semicolon (x_i)_{i \in I} \mapsto (\mappt{f_i}{x_i})_{i \in I} $が閉写像ならば
対応済み

2022-01-09 08:37 UTC, CptHaus commented on documents/catalog/theories/closed-maps.tex
> +
対応済み

2022-01-09 08:38 UTC, CptHaus commented
ここまでのコメントに対応しました.
確認をお願いします.

2022-01-09 09:22 UTC, ykyki commented
OK 🍻

2022-01-09 09:23 UTC, ykyki approved these changes

2022-01-09 09:23 UTC, merged