連結空間の積が連結になることの証明
ykyki/extop-tex pull request #87
Opened 2021-11-27 06:30 UTC by CptHaus

## 背景・意図

- 連結性のセクションの充実

## したこと

- 連結空間の積空間が連結になることの証明
- 上の証明に関連する命題の証明

## してないこと

## プルリク提出前: 確認事項

- [ ] 変更箇所の動作確認・表示確認
- [ ] reviewersやassignees等の設定
- [ ] このプルリクのプレビュー
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] 以上の項目がチェックされているか

## レビュー進行状態

1. [ ] 文章の配置場所やレイアウト
2. [ ] 数学的な内容
3. [ ] 出典の記載
4. [ ] 誤植や言葉使いなど文章の細部
5. [ ] コマンドの使い方
6. [ ] ソースコードのフォーマット

2021-12-11 09:44 UTC, ykyki reviewed
以下の観点でレビューを終えました:

- 数学的な内容

2021-12-11 09:44 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ x \in \topcl A $となる.
自分で読んで補完することはできますが、証明の書き方にちょっと欠けている部分があります。

自分なりに補完すると、この証明はおおまかに次のステップになると思います。

1. xの任意の近傍がA_pと交わることを示せば良い
2. `\bigcap_{\lambda \in \Lambda'} \mapinvset{p_\lambda}{U_\lambda}`のタイプの開集合全体がxの近傍基となる
3. このタイプの開集合は必ずA_pと交わる

この内、ステップ3については書かれていますが、ステップ1, 2も欠かすことができません。
そこでステップ1, 2に相当する内容の追記をお願いします。

2021-12-11 09:44 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
>  	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続であることからわかる.
連結性より空でないことが保証されていることもポイントなので、追記お願いします。

2021-12-11 09:44 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ n = 1 $のときは明らかであり, $ n-1 $のとき定理が成り立つと仮定する.
n = 0の場合も注意しておきたいです。

2021-12-11 09:44 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	\cref{c00003}より$ X $は連結である.
```suggestion
	次に, $ \Lambda $が一般の場合について示す.
	$ X $の1点$ p $をとる.
	$ A_p $を\cref{p00011}と同様に定義する.
	$ A_p $が連結であることを示せば,
	\cref{c00003}より$ X $は連結である.
```

2021-12-11 09:44 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	{x_\lambda = p_\lambda, \lambda \notin \Lambda'} $と表せる.
```suggestion
	{\text{任意の$\lambda \in \Lambda \setminus \Lambda'$について$x_\lambda = p_\lambda$}} $と表せる.
```

条件は正確に書きましょう。

また、この条件で定義される部分集合をすぐ下でも使っているようなので、何かしら記号を割り当てておいてもよさそうです。

2021-12-25 04:36 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ x \in \topcl A $となる.
対応済み

2021-12-25 04:36 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
>  	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続であることからわかる.
対応済み

2021-12-25 04:36 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ n = 1 $のときは明らかであり, $ n-1 $のとき定理が成り立つと仮定する.
対応済み

2021-12-25 04:36 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	\cref{c00003}より$ X $は連結である.
対応済み

2021-12-25 04:36 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	{x_\lambda = p_\lambda, \lambda \notin \Lambda'} $と表せる.
対応済み

2022-01-09 09:50 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
>  	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続であることからわかる.
「射影が連続」だけよりも「射影が連続全射」と述べておいた方が根拠が明確になります。連結性が連続写像によって保たれることは記載済みなので。

2022-01-09 09:55 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ n = 1 $のときは明らかであり, $ n-1 $のとき定理が成り立つと仮定する.
`\Lambda`が空か非空であるかで分けて話を進めるよりも、

一般性を失うことなく `\Lambda = \{1, 2, \cdots, n\}`と仮定してよい。nに関する帰納で示す。n=0の場合…

というように書いた方がスッキリすると思います。修正をお願いします 🙇 。

2022-01-09 09:55 UTC, ykyki commented
rechecked

2022-01-16 03:37 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
>  	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続であることからわかる.
対応済み

2022-01-16 03:37 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ n = 1 $のときは明らかであり, $ n-1 $のとき定理が成り立つと仮定する.
対応済み

2022-01-16 04:21 UTC, ykyki reviewed
rechecked

2022-01-16 04:21 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続全射であることからわかる.
163, 164行目があれば162行目は不要ですね。削除をお願いします。

2022-01-16 05:08 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	射影$ \morph{p_\lambda}{X}{X_\lambda} $が連続全射であることからわかる.
対応済み

2022-01-22 06:36 UTC, ykyki requested changes
以下の観点についてレビューを終えました:
- 出典の記載
- 誤植や言葉使いなど文章の細部

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +
不必要な空行です。一行削除をお願いします。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +\end{proposition}
よく見かける定理ではない気がします。出典記載を一応お願いします。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ \morph{p_\lambda}{X}{X_\lambda} $を射影とする.
```suggestion
	$ \setfamily{X_\lambda}{\lambda \in \Lambda} $を位相空間の族,
	$ X \defeq \prod_{\lambda \in \Lambda} X_\lambda $を積空間,
	$ \morph{p_\lambda}{X}{X_\lambda} $を射影とする.
```

こんな感じでリズムを整えると読みやすくなりそうです。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	{\setcomp{\lambda \in \Lambda}{x_\lambda \neq p_\lambda} \text{が有限}} $と定める.
A_pの定義がちょっと長いので、インライン数式ではなくディスプレイ数式に変更をお願いします。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	U_\lambda \in \mathcal{O}_\lambda, x_\lambda \in U_\lambda} $
こちらも長い定義なのでディスプレイ数式に変更お願いします。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	このとき$ X = \topcl A_p $が成り立つ.
```suggestion
	このとき, $ X = \topcl A_p $が成り立つ.
```

周辺の書き方と合わせるために、ここもカンマ追加をお願いします。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
>  	位相空間の族$ \setfamily{X_\lambda}{\lambda \in \Lambda} $について,
ここで文を一度区切りましょう。

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ n-1 $のとき定理が成り立つと仮定する.
```suggestion
	$ n-1 $のとき主張が成り立つと仮定する.
```

定理ではないですね。「主張」とするのはどうでしょうか？

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
```suggestion
	帰納法の仮定より
	$ A \defeq \{x_1\} \times X_2 \times \cdots \times X_n $,
	$ B \defeq X_1 \times \cdots \times X_{n-1} \times \{y_n\} $
	は連結部分集合である.
	$ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
```

2022-01-22 06:36 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
暗に命題を使っているので、参照を明示しておきましょう。

2022-01-29 05:13 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +\end{proposition}
森田さんの定理14.11に主張があります.

2022-01-29 05:13 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +
対応済み

2022-01-29 05:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ \morph{p_\lambda}{X}{X_\lambda} $を射影とする.
対応済み

2022-01-29 05:19 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	{\setcomp{\lambda \in \Lambda}{x_\lambda \neq p_\lambda} \text{が有限}} $と定める.
対応済み

2022-01-29 05:19 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	U_\lambda \in \mathcal{O}_\lambda, x_\lambda \in U_\lambda} $
対応済み

2022-01-29 05:20 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	このとき$ X = \topcl A_p $が成り立つ.
対応済み

2022-01-29 05:21 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
>  	位相空間の族$ \setfamily{X_\lambda}{\lambda \in \Lambda} $について,
対応済み

2022-01-29 05:22 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ n-1 $のとき定理が成り立つと仮定する.
対応済み

2022-01-29 05:25 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
参照先としてどの命題を想定していますか?

2022-01-29 05:50 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
c00001。 連結部分集合の合併が連結になる命題。

2022-01-29 06:43 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので
対応済み

2022-02-18 12:34 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	{\setcomp{\lambda \in \Lambda}{x_\lambda \neq p_\lambda} \text{が有限}} $と定める.
ディスプレイ数式にするときには `$$ ~ $$` ではなく `\[ ~ \]` にするようにしましょう。

2022-02-18 12:38 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	{\setcomp{\lambda \in \Lambda}{x_\lambda \neq p_\lambda} \text{が有限}} $と定める.
作成: https://github.com/ykyki/extop-tex/pull/113

2022-02-18 12:39 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	U_\lambda \in \mathcal{O}_\lambda, x_\lambda \in U_\lambda} $
上と同じくディスプレイ数式の書き方の変更をお願いします。

2022-02-18 13:07 UTC, ykyki requested changes
以下の観点でレビューを終えました。

- コマンドの使い方

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	積位相の定義より, $$ \setcomp{\bigcap_{\lambda \in \Lambda'} \mapinvset{p_\lambda}{U_\lambda}}
ディスプレイ数式を入れるときにはソースコードでも改行するようにしましょう。

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	U_\lambda \in \mathcal{O}_\lambda, x_\lambda \in U_\lambda} $$
```suggestion
	{\text{$\Lambda'$は$\Lambda$の有限部分集合},
	\text{$U_\lambda$は$x_\lambda$の開近傍}} $$
```

略記としてのコロンは正式な文章としては避けたいです。

また数式中のテキストですが、テキスト部分だけ `\text{~}` で囲むのは見づらくセマンティクスとしても不適当な気がするので、このような書き方はどうでしょうか？

ついでに `$ \mathcal{O}_\lambda $` の定義も削減できそうです。

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	このとき, $ y \in A_p \cap \left[\bigcap_{\lambda \in \Lambda'}
定義済みの`\lrbrack`を使いましょう。

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	一般性を失うことなく$ \Lambda = \{1, 2, \cdots, n\} $と仮定してよい.
```suggestion
	一般性を失うことなく$ \Lambda = \{1, 2, \ldots, n\} $と仮定してよい.
```

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	任意に$ X $の2点$ x = (x_1, \cdots, x_n), y = (y_1, \cdots, y_n) $をとる.
```suggestion
	任意に$ X $の2点$ x = (x_1, \ldots, x_n), y = (y_1, \ldots, y_n) $をとる.
```

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	B \defeq X_1 \times \cdots \times X_{n-1} \times \{y_n\} $は
`\lrbrace`を使いましょう。

2022-02-18 13:07 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので,
```suggestion
	連結部分集合である. $ (x_1, x_2, \ldots, x_{n-1}, y_n) \in A \cap B $なので,
```

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	積位相の定義より, $$ \setcomp{\bigcap_{\lambda \in \Lambda'} \mapinvset{p_\lambda}{U_\lambda}}
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	U_\lambda \in \mathcal{O}_\lambda, x_\lambda \in U_\lambda} $$
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	このとき, $ y \in A_p \cap \left[\bigcap_{\lambda \in \Lambda'}
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	一般性を失うことなく$ \Lambda = \{1, 2, \cdots, n\} $と仮定してよい.
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	任意に$ X $の2点$ x = (x_1, \cdots, x_n), y = (y_1, \cdots, y_n) $をとる.
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	B \defeq X_1 \times \cdots \times X_{n-1} \times \{y_n\} $は
対応済み

2022-02-18 14:14 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	連結部分集合である. $ (x_1, x_2, \cdots, x_{n-1}, y_n) \in A \cap B $なので,
対応済み

2022-03-13 05:02 UTC, ykyki requested changes
rechecked:
- コマンドの使い方

2022-03-13 05:02 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	\end{cases}$$
`$$`の書き直しをお願いします。

2022-03-13 05:02 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	$ x $任意の開近傍が$ A_p $と交わることが示された.
```suggestion
	$ x $の任意の開近傍が$ A_p $と交わることが示された.
```

2022-03-13 05:02 UTC, ykyki commented on documents/catalog/theories/connected-spaces.tex
> +	任意に$ X $の2点$ x = (x_1, \ldots, x_n), y = (y_1, \cdots, y_n) $をとる.
```suggestion
	任意に$ X $の2点$ x = (x_1, \ldots, x_n), y = (y_1, \ldots, y_n) $をとる.
```

2022-03-22 12:44 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	\end{cases}$$
対応済み

2022-03-22 12:44 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	$ x $任意の開近傍が$ A_p $と交わることが示された.
対応済み

2022-03-22 12:44 UTC, CptHaus commented on documents/catalog/theories/connected-spaces.tex
> +	任意に$ X $の2点$ x = (x_1, \ldots, x_n), y = (y_1, \cdots, y_n) $をとる.
対応済み

2022-03-22 12:59 UTC, ykyki approved these changes

2022-03-22 13:00 UTC, ykyki commented
OK! 🍻

2022-03-22 13:00 UTC, merged