パラコンパクト空間に関する命題の証明
ykyki/extop-tex pull request #91
Opened 2021-12-18 03:59 UTC by CptHaus

## 背景・意図

- パラコンパクト空間に関する命題の証明

## したこと

- 命題: パラコンパクト空間と局所コンパクトハウスドルフなパラコンパクト空間の積はパラコンパクト
- 命題: T4空間の部分集合を同一視してできる商空間の分離性について

## してないこと

- 他の命題の証明

## 参考資料

- 児玉・永見

## プルリク提出前: 確認事項

- [ ] 変更箇所の動作確認・表示確認
- [ ] reviewersやassignees等の設定
- [ ] このプルリクのプレビュー
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] 以上の項目がチェックされているか

## リバイズ進行状態

1. [ ] 文章の配置場所やレイアウト
2. [ ] 数学的な内容
3. [ ] 出典の記載
4. [ ] 誤植や言葉使いなど文章の細部
5. [ ] コマンドの使い方
6. [ ] ソースコードのフォーマット

2022-01-29 05:42 UTC, ykyki requested changes
以下の点でレビューしました:
- 文章の配置場所やレイアウト
- 数学的な内容

> 命題: パラコンパクト空間と局所コンパクトハウスドルフなパラコンパクト空間の積はパラコンパクト

この証明の概略はファローしたのですが、細かい部分までチェックできていないので、また後でチェックします。

2022-01-29 05:42 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +
証明OK

2022-01-29 05:42 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	分離されることが示せる.
この部分は命題 2.2.7で似たようなことを証明しているので、そちらにまとめてしまってもいいかも。

2022-01-29 05:42 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	\topT{1} な$ X / A $はパラコンパクトである.
Lindelof が商写像で保たれることを命題として切り出してしまいましょう。
それ以外はOKです。

2022-01-29 05:42 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	したがって, $ \bigcup_{V \in \mathscr{V}} \mathscr{W}_V $は局所有限である.
この部分をひとつのパラグラフに切り出して、パラグラフ頭に結論を持ってきてもらった方が、議論の流れがわかりやすい気がします。対応よろしくお願いします。

2022-03-13 04:58 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	分離されることが示せる.
T4リンデーレーフ空間Xの商空間X/Aがパラコンパクトになるという主張に変更し, X/AがT4であることは命題2.2.7の結果を引用しました.

2022-03-13 05:00 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	\topT{1} な$ X / A $はパラコンパクトである.
"Lindelof が商写像で保たれること"はLindelof空間のセクションの地の文に書いてあるのでこのような書き方になっています. 形式を重視してかんたんな主張も命題として引用するのであれば地の文の運用方法の見直しも考える必要があります.

2022-03-13 05:01 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	したがって, $ \bigcup_{V \in \mathscr{V}} \mathscr{W}_V $は局所有限である.
対応しました.

2022-04-02 12:50 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	\topT{1} な$ X / A $はパラコンパクトである.
地の文で書いてあるなら切り出ししなくてもOKです。
もっと一般に連続全射で保たれるので、そのように書いてもいいかも。

2022-04-02 13:49 UTC, ykyki requested changes

2022-04-02 13:49 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ V \in \mathscr{V}_p $ならば$ p \in X \times \topcl_Y V $となるように$ U_p $をとることができる.
`V_p`の定義が`U_p`に依存しているので、ここの主張を読むときの負荷が大きかったです。
ステップ分けして書いてももらえないでしょうか？

2022-04-09 10:45 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ V \in \mathscr{V}_p $ならば$ p \in X \times \topcl_Y V $となるように$ U_p $をとることができる.
対応しました.

2022-04-16 10:53 UTC, ykyki requested changes
rechecked:

2022-04-16 10:53 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ \mathscr{V}_p \defeq \setcomp{X \times \topcl_Y V}{V \in \mathscr{V}, p \in V} $
`p \in V` は誤植？ (p は X \times Yの元のはず）

2022-04-16 10:53 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	各$ V \in \mathscr{V}_p $について$ \mathscr{W}_V $は局所有限なので, $ p $の開近傍$ U_p \subset U_p $
```suggestion
	各$ V \in \mathscr{V}_p $について$ \mathscr{W}_V $は局所有限なので, $ p $の開近傍$ U'_p \subset U_p $
```

2022-04-23 10:27 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ \mathscr{V}_p \defeq \setcomp{X \times \topcl_Y V}{V \in \mathscr{V}, p \in V} $
対応済み

2022-04-23 10:27 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	各$ V \in \mathscr{V}_p $について$ \mathscr{W}_V $は局所有限なので, $ p $の開近傍$ U_p \subset U_p $
対応済み

2022-04-23 11:31 UTC, ykyki commented
OK: 数学的な内容

2022-04-23 11:31 UTC, ykyki commented
出典の記載: 今回はゼロ個なのでOK

2022-04-23 11:39 UTC, ykyki requested changes

2022-04-23 11:39 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ X \times \topcl_Y V $の開被覆である. このとき, $ X \times \topcl_Y V $の
文末で改行

2022-04-23 11:39 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ \setcomp{X \times \topcl_Y V}{V \in \mathscr{V}} $は$ X \times Y $の局所有限被覆である.
`$ \setcomp{X \times \topcl_Y V}{V \in \mathscr{V}} $` が何度も出てくるので、記号を導入してより読みやすくしたいです。

2022-04-23 11:39 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	と定めると$ \mathscr{W} $は$ X \times Y $の局所有限な開被覆であり, $ \mathscr{W} < \mathscr{U} $を満たす.
```suggestion
	と定めると$ \mathscr{W} $は$ X \times Y $の局所有限な開被覆であり, $ \mathscr{W} \refines \mathscr{U} $を満たす.
```

2022-04-23 11:39 UTC, ykyki commented on documents/catalog/theories/paracompact-spaces.tex
> +	\topT{4} \Lindelof 空間$ X $と閉部分集合$ A $に対して, $ A $の元を同一視した商空間を$ X / A $とする.
数学的内容: 細かいことですが、Aが空でないと仮定しておきたいです。

2022-04-23 11:40 UTC, ykyki commented
✅  誤植や言葉使いなど文章の細部

2022-05-15 09:54 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ X \times \topcl_Y V $の開被覆である. このとき, $ X \times \topcl_Y V $の
対応しました.

2022-05-15 09:54 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	$ \setcomp{X \times \topcl_Y V}{V \in \mathscr{V}} $は$ X \times Y $の局所有限被覆である.
対応しました.

2022-05-15 09:54 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	と定めると$ \mathscr{W} $は$ X \times Y $の局所有限な開被覆であり, $ \mathscr{W} < \mathscr{U} $を満たす.
対応しました.

2022-05-15 09:54 UTC, CptHaus commented on documents/catalog/theories/paracompact-spaces.tex
> +	\topT{4} \Lindelof 空間$ X $と閉部分集合$ A $に対して, $ A $の元を同一視した商空間を$ X / A $とする.
対応しました.

2022-05-15 09:57 UTC, CptHaus commented
レビューコメントに対応しました.
確認をお願いします.

2022-05-15 11:01 UTC, ykyki approved these changes
OK🍷

2022-05-15 11:04 UTC, merged