可算性に関する章とセクションの追加
ykyki/extop-tex pull request #95
Opened 2021-12-25 05:43 UTC by CptHaus

## 背景・意図

- 可算性に関する章とセクションの追加

## したこと

- 可算性に関する各性質の定義の記述

## してないこと

- 各性質の強弱関係や命題の記述

## Linked Issues

- resolve #92
- close #92

## プルリク提出前: 確認事項

- [ ] 変更箇所の動作確認・表示確認
- [ ] reviewersやassignees等の設定
- [ ] このプルリクのプレビュー
- [ ] プルリクのタイトルがブランチ名のままになっていないか
- [ ] 以上の項目がチェックされているか

## リバイズ進行状態

1. [ ] 文章の配置場所やレイアウト
2. [ ] 数学的な内容
3. [ ] 出典の記載
4. [ ] 誤植や言葉使いなど文章の細部
5. [ ] コマンドの使い方
6. [ ] ソースコードのフォーマット

2022-01-09 08:24 UTC, ykyki requested changes
[投稿ミスのため削除]

2022-01-09 08:30 UTC, ykyki commented
次の観点までレビューOK 👍 です:
- 文章の配置場所やレイアウト
- 数学的な内容

2022-01-09 08:31 UTC, ykyki commented
出典も今のところすぐには必要ないのでOKです。

2022-01-09 09:07 UTC, ykyki requested changes
次の観点でレビューを終えました:
- 誤植や言葉使いなど文章の細部

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/Frechet-spaces.tex
> +	$ a $に収束するものが存在することをいう.
定義文の書き方一般の話ですが、パターンとして

1. 「〇〇であるとは、□□ことである。」
2. 「〇〇であるとは、□□ことをいう。」

の2つがありますが、なるべく形式を統一しておきたいので、言い回しの自然さを損なわない範囲で前者の方に合わせるようにしましょう。 #96

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/countable-chain-condition.tex
> +	$ X $における交わらない開集合からなる族は高々可算な開集合族である.
```suggestion
	$ X $の互いに交わらない開集合からなる任意の部分集合族が可算な集合族になることである.
```

ニュアンスとしては異なりますが、「高々可算」だと少し冗長な感じがするので「可算」で十分だと思います。 #96

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/first-countable-spaces.tex
> +	位相空間$ X $が\indexjj{だいいちかさん}{第一可算}{first countable}であるとは,
「第一可算条件を満たす」という書き方も述べておきたいです。（cf. 森田位相）

「第一可算」or「第1可算」の表記については、前者で統一する方針にしましょう。

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/second-countable-spaces.tex
> +	位相空間$ X $が\indexjj{だいにかさん}{第二可算}{second countable}であるとは,
「第二可算公理を満たす」をこちらでも追加しましょう。

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/first-countable-spaces.tex
> +	任意の点$ x \in X $について可算な近傍基が存在することをいう.
語尾: 「〜ことである。」

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/second-countable-spaces.tex
> +	可算な開集合基が存在することをいう.
語尾: 「〜ことである。」

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/separable-spaces.tex
> +	可算な稠密部分集合が存在することをいう.
語尾: 「〜ことである。」

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/sequential-spaces.tex
> +	$ A $内の任意の点列$ (a_n)_{n \in \N} $についてその極限点が$ A $に属することをいう.
極限点はたしか未定義な用語だったはず。定義が紛らわしい用語なので使用は控えたいです。
そこでこの用語を使わないように書き直しをお願いします。

細かいことをいうと、「$X$における極限点」のように書かないと意味がやや曖昧であると思いました。。（前後を読めば分かりますが）

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/sequential-spaces.tex
> +	任意の列型閉集合が閉集合であるとき\indexjj{れつがた}{列型}{sequential}であるという.
語尾: 「〜ことである。」

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/strongly-Frechet-spaces.tex
> +	位相空間$ X $が\indexjj{きょう\Frechet}{強 \Frechet}{strongly \Frechet}であるとは,
```suggestion
	位相空間$ X $が\indexjj{きょうFrechet}{強\Frechet}{strongly \Frechet}であるとは,
```

2022-01-09 09:07 UTC, ykyki commented on documents/catalog/theories/strongly-Frechet-spaces.tex
> +	任意の$ n \in \N $について$ a_n \in A_n $を満たすものが存在することをいう.
語尾: 「〜ことである。」

2022-01-09 09:54 UTC, CptHaus commented on documents/catalog/theories/Frechet-spaces.tex
> +	$ a $に収束するものが存在することをいう.
対応済み

2022-01-09 09:54 UTC, CptHaus commented on documents/catalog/theories/countable-chain-condition.tex
> +	$ X $における交わらない開集合からなる族は高々可算な開集合族である.
対応済み

2022-01-09 09:54 UTC, CptHaus commented on documents/catalog/theories/first-countable-spaces.tex
> +	位相空間$ X $が\indexjj{だいいちかさん}{第一可算}{first countable}であるとは,
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/second-countable-spaces.tex
> +	位相空間$ X $が\indexjj{だいにかさん}{第二可算}{second countable}であるとは,
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/first-countable-spaces.tex
> +	任意の点$ x \in X $について可算な近傍基が存在することをいう.
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/second-countable-spaces.tex
> +	可算な開集合基が存在することをいう.
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/separable-spaces.tex
> +	可算な稠密部分集合が存在することをいう.
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/sequential-spaces.tex
> +	$ A $内の任意の点列$ (a_n)_{n \in \N} $についてその極限点が$ A $に属することをいう.
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/sequential-spaces.tex
> +	任意の列型閉集合が閉集合であるとき\indexjj{れつがた}{列型}{sequential}であるという.
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/strongly-Frechet-spaces.tex
> +	位相空間$ X $が\indexjj{きょう\Frechet}{強 \Frechet}{strongly \Frechet}であるとは,
対応済み

2022-01-09 09:55 UTC, CptHaus commented on documents/catalog/theories/strongly-Frechet-spaces.tex
> +	任意の$ n \in \N $について$ a_n \in A_n $を満たすものが存在することをいう.
対応済み

2022-01-09 09:56 UTC, CptHaus commented
コメントいただいた箇所については修正完了しました.

2022-01-16 03:55 UTC, ykyki requested changes
rechecked

2022-01-16 03:55 UTC, ykyki commented on documents/catalog/theories/first-countable-spaces.tex
> +	\indexjj{だいいちかさん}{第一可算}{first countable}であるという.
他の定義の書き方と形式を統一するために

「位相空間Xが第一可算条件を満たす, または第一可算であるとは, ~」

という書き方でお願いします。

2022-01-16 03:55 UTC, ykyki commented on documents/catalog/theories/first-countable-spaces.tex
> +	\indexjj{だいいちかさん}{第一可算}{first countable}であるという.
「第一可算条件」よりも「第一可算公理」という用語の方が適切だと思います。(cf. 森田位相)

2022-01-16 03:55 UTC, ykyki commented on documents/catalog/theories/first-countable-spaces.tex
> +	\indexjj{だいいちかさん}{第一可算}{first countable}であるという.
「第一可算公理」と「第一可算」の両方に `\indexjj` を付けてください。

2022-01-16 03:55 UTC, ykyki commented on documents/catalog/theories/second-countable-spaces.tex
> +	indexjj{だいにかさん}{第二可算}{second countable}であるという.
第一可算の指摘と同様の修正をお願いします。

2022-01-22 06:27 UTC, CptHaus commented on documents/catalog/theories/first-countable-spaces.tex
> +	\indexjj{だいいちかさん}{第一可算}{first countable}であるという.
対応済み

2022-01-22 06:27 UTC, CptHaus commented on documents/catalog/theories/second-countable-spaces.tex
> +	indexjj{だいにかさん}{第二可算}{second countable}であるという.
対応済み

2022-01-29 04:12 UTC, ykyki commented
OK: 誤植や言葉使いなど文章の細部

2022-01-29 04:16 UTC, ykyki commented
ひとまずOK: コマンドの使い方

2022-01-29 04:21 UTC, ykyki commented
表記ゆれが気になったのでタスクを作成: https://github.com/ykyki/extop-tex/issues/105

2022-01-29 04:26 UTC, ykyki commented
OK: ソースコードのフォーマット

2022-01-29 04:27 UTC, ykyki approved these changes

2022-01-29 04:27 UTC, ykyki commented
OK! 🍻

2022-01-29 04:28 UTC, merged